excel_header = [
	'Date',
	'Day',
	'Monkey',
	'Task',
	'Session Number',
	'Start Time',
	'End Time',
	'Duration',
	'Total Trials',
	'Correct Trials',
	'Attempts/Min',
	'Percent Initiated',
	'Percent Correct',	
	'Reward Drops - Large',
	'Reward Freq - Large',
	'Reward Duration - Large',
	'Reward Drops - Small',
	'Reward Freq - Small',
	'Reward Duration - Small',
	'Airpuff Pulses - Large',
	'Airpuff Freq - Large',
	'Airpuff Pulses - Small',
	'Airpuff Freq - Small',
	'Lick - Large Reward',
	'Lick - Small Reward',
	'Lick - Small Airpuff',
	'Lick - Large Airpuff',
	'Blink - Large Reward',
	'Blink - Small Reward',
	'Blink - Small Airpuff',
	'Blink - Large Airpuff',
]